#!/bin/bash

# Copyright (C) 2024-2026 Burak Günaydin
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

workspace_directory=$(dirname "$(readlink -f "$0")") # teatype/scripts/deploy
parent_directory=$(dirname "$workspace_directory") # teatype/scripts
grandparent_directory=$(dirname "$parent_directory") # teatype
. "$grandparent_directory/util/bash-helper.sh"

prepare_sudo_env

cleanup() {
    sudo rm -rf "$grandparent_directory/dist/llama-cpp-python"
}
implemented_trap cleanup

cd "$grandparent_directory"
. teatype-venv/bin/activate

mkdir -p "$grandparent_directory/dist"
cd "$grandparent_directory/dist"

sudo apt-get update -y
sudo apt-get install -y build-essential cmake python3-dev python3-pip git ninja-build libcurl4-openssl-dev gcc-12 g++-12 libgomp1
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 --slave /usr/bin/g++ g++ /usr/bin/g++-12
sudo apt-get autoremove -y

if [ -d "llama-cpp-python" ]; then
    echo "llama-cpp-python directory already exists, skipping cloning"
else
    git clone --recurse-submodules https://github.com/abetlen/llama-cpp-python.git
fi
cd "$grandparent_directory/dist/llama-cpp-python"

# Set environment variables for the build
export CMAKE_ARGS="-DGGML_CUDA=off"
export FORCE_CMAKE=1
export CC="/usr/bin/gcc-12"
export CXX="/usr/bin/g++-12"

# Run the installation from the cloned directory
python3.13 -m pip install --no-cache-dir .